### PR TITLE
Fix the import of MutableSequence causing cytomine import to fail wit…

### PR DESCRIPTION
**Pull request by benjamindorra**
…h Python 3.10

I could only test the code on python 3.10 and 3.8 but it should not cause problems on earlier versions.

### CODE REVIEW

**Comment by urubens** [comment]
Thanks for your PR, I confirm it should not cause issues on earlier version, and I guess it should be merged soon. I'm sure @geektortoise will review it soon :).

**Comment by geektortoise** [comment]
Hello @benjamindorra !
Thanks for your PR !
It is the occasion to introduce @chlmarchal : our Pythonista in the Cytomine company team. :-)

**Comment by benjamindorra** [comment]
Hello, thanks for your quick review ! It has been merged.
-------- Message d'origine --------De : Ulysse Rubens ***@***.***> Date : 02/05/2022  11:46  (GMT+01:00) À : cytomine/Cytomine-python-client ***@***.***> Cc : benjamindorra ***@***.***>, Author ***@***.***> Objet : Re: [cytomine/Cytomine-python-client] Fix the import of MutableSequence causing cytomine import to fail wit… (PR #45) 
Thanks for your PR, I confirm it should not cause issues on earlier version, and I guess it should be merged soon. I'm sure @geektortoise will review it soon :).

**Comment by benjamindorra** [comment]
Hello geektortoise ! Thank you for the merge :)
-------- Message d'origine --------De : geektortoise ***@***.***> Date : 04/05/2022  10:00  (GMT+01:00) À : cytomine/Cytomine-python-client ***@***.***> Cc : benjamindorra ***@***.***>, Mention ***@***.***> Objet : Re: [cytomine/Cytomine-python-client] Fix the import of MutableSequence causing cytomine import to fail wit… (PR #45) 
Hello @benjamindorra !
Thanks for your PR !
It is the occasion to introduce @chlmarchal : our Pythonista in the Cytomine company team. :-)

**Pull request merged**
